# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: custom
  theme_night:
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ''
    org_name: 'ICOPS'
    description: 'International Committee on Open Phytolith Science - Community building and training initiative for the Phytolith Community.'
    twitter: 'https://twitter.com/open_phytoliths'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: 'Â© {year} ICOPS. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jun 8, 2022'
  time_format: '8:04 PM'

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/open-phytoliths/open-phytoliths-website'
    content_dir: content
    branch: main
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: ICOPS
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
